### ISSUE TITLE
Cannot make ice cubes

### ISSUE THREAD

**Issue by SweetKittyKaty** [0xKalKYS/WilderWorld#1]
Good morning,
I have encountered a problem. there is no recipe for making ice cubes. I have searched for a while but found no solution to this error. I even checked the source and there is something you call "slush cauldron" I thought normal cauldron will be enough but it seems to never work. Can you please tell me what I am doing wrong, eventually say a way how to obtain this item?

thank you in advance 
Kate

**Comment by 0xKY** [comment]
Thanks for asking; I should have added an explanation in the description.

Right clicking a cauldron, containing water, with ice, makes slush. You can then right click the cauldron to take out ice cubes or put them back in.

**Comment by SweetKittyKaty** [comment]
Hi! 
It still has the problem. I tried this thing you have written, even saw it in some comment section however it doesnt work.
Fill cauldron with water is no problem, but right clicking it with ice only places the ice block on the top of it. It doesnt create slush. either it placed on top of the cauldron or from the side. 

I am using the Medieval minecraft fabric 1.18 version 12v for better context

**Comment by 0xKY** [comment]
Fixed in the next update
