### ISSUE TITLE
1.18.2 ice cube can be obtained indefinitely

### ISSUE THREAD

**Issue by QianFuv** [0xKalKYS/WilderWorld#10]
Right-clicking a pot with an ice cube does not reduce the number of ice cubes held.

**Comment by QianFuv** [comment]
@0xKY plz check！

**Comment by 0xKY** [comment]
Fixed in the next update

**Comment by QianFuv** [comment]
> Fixed in the next update

Sorry to bother you, can you release a fix for 1.18.2? This bug is very serious on my server!

**Comment by 0xKY** [comment]
Sorry, I would like to but I want to focus on the 1.20 version and I don't plan on updating previous versions. The 1.20 version should fix most of the bugs from previous versions and will polish a lot of the old features, so I would recommend switching to it when it releases, as soon as you can, if possible.
