### ISSUE TITLE
Wisteria Door has no textures and Birch Saplings have opposite growth patterns

### ISSUE THREAD

**Issue by VeggeieDude** [0xKalKYS/WilderWorld#2]
Hey! Wisteria doors have no textures for me and come out as the default purple and black checkers box texture.
Also when I plant a single birch sapling, it grows into a giant Aspen tree, and if I do the 2x2 pattern it'll turn into a normal birch tree

I'm using version 2.3.0 on Fabric 1.19

**Comment by 0xKY** [comment]
Fixed in the next update
