### ISSUE TITLE
[1.18.2] Generation Issue

### ISSUE THREAD

**Issue by Khytwel** [0xKalKYS/WilderWorld#3]
Hi,

There is a small problem with the generation of trees on the last version 2.2.2, it seems that the problem is not present in 1.19.

![image](https://user-images.githubusercontent.com/54046029/178516538-c4c652f4-71ec-45cf-951c-26b8a38c1029.png)

I also take the opportunity to point out that it would be a good thing to lower the volume of the butterfly noise a little :)

**Comment by 0xKY** [comment]
Fixed in the next update
