### ISSUE TITLE
Butterflies constantly spawning and dying

### ISSUE THREAD

**Issue by MaskedElephant** [0xKalKYS/WilderWorld#5]
Hello, I am currently running a server on Medieval Minecraft [Fabric] for 1.18. Butterflies have been consistently spawning but they almost instantly die for no apparent reason and drop tons of butterfly wings. I have try to deal with the issue by clearing the ground of the item, but they always come back. I also tried to disable the spawning of the wings in the config of the server but was not able to find the file. If there is a file and I just happened to miss it or there is an easy solution. I'd love to hear it (:

**Comment by 0xKY** [comment]
Fixed in the next update
